version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: "0.1.x"
    milestone: 29
    ignore:
      # metrics are better with https://github.com/Netflix/Hystrix/pull/1568 introduced
      # in hystrix 1.5.12, but Netflix re-released 1.5.11 as 1.5.18 late in 2018.
      # <=1.5.11 or 1.5.18 doesn't break with Micrometer, but open metrics won't be correct necessarily.
      - dependency-name: "com.netflix.hystrix:hystrix-core"
      # only upgrade patch versions
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 30
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: "0.2.x"
    milestone: 28
    ignore:
      # metrics are better with https://github.com/Netflix/Hystrix/pull/1568 introduced
      # in hystrix 1.5.12, but Netflix re-released 1.5.11 as 1.5.18 late in 2018.
      # <=1.5.11 or 1.5.18 doesn't break with Micrometer, but open metrics won't be correct necessarily.
      - dependency-name: "com.netflix.hystrix:hystrix-core"
      # only upgrade patch versions
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 30
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: "main"
    milestone: 2
    ignore:
      # metrics are better with https://github.com/Netflix/Hystrix/pull/1568 introduced
      # in hystrix 1.5.12, but Netflix re-released 1.5.11 as 1.5.18 late in 2018.
      # <=1.5.11 or 1.5.18 doesn't break with Micrometer, but open metrics won't be correct necessarily.
      - dependency-name: "com.netflix.hystrix:hystrix-core"
      # upgrade minor and patch versions on main
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 50
# Triggering dependabot
